@startuml
start
:Сбор данных;
:Преобразование данных в csv-формат;
:Подготовка данных;
:Анализ данных;
fork
    :анализ по тегам "интерсеное/неинтересное";
fork again
    :анализ по просмотрам видео;
fork again
    :анализ по лайкам;
end fork
:Найдены понравившиеся видео и жанры;
:Выдача рекомендаций;
stop
@enduml