@startuml
start
:Загрузка видео;
:Добавление названия видео;
:Добавление описания к видео;
:Добавление возрастного ограничения;
:Добавление тэгов к видео;
:Добавления настроек комментирования видео;
:Публикация видео;
stop
@enduml