@startuml
[*] --> Незагруженное_Видео
state "Загруженное Видео" as Видео
Незагруженное_Видео --> Видео : Загрузка видео

state "Загруженное Видео" as Видео_Название
Видео --> Видео_Название : Добавили название видео
Видео_Название : Название 

state "Загруженное Видео" as Видео_Описание
Видео_Название --> Видео_Описание : Добавили описание к видео
Видео_Описание : Название
Видео_Описание : Описание

state "Загруженное Видео" as Видео_Возраст
Видео_Описание --> Видео_Возраст : Добавили возрастное ограничение к видео
Видео_Возраст : Название
Видео_Возраст : Описание
Видео_Возраст : Возрастное ограничение

state "Загруженное Видео" as Видео_Теги
Видео_Возраст --> Видео_Теги : Добавили теги к видео
Видео_Теги : Название
Видео_Теги : Описание
Видео_Теги : Возрастное ограничение
Видео_Теги : Теги

state "Загруженное Видео" as Видео_Комментарии
Видео_Теги --> Видео_Комментарии : Добавили настройки комментариев к видео
Видео_Комментарии : Название
Видео_Комментарии : Описание
Видео_Комментарии : Возрастное ограничение
Видео_Комментарии : Теги
Видео_Комментарии : Настройки комментариев

state "Публикация видео" as Публикация
Видео_Комментарии --> Публикация
@enduml