@startuml
start
:Создание заявки;
:Обработка заявки;
:Проверка геолокации;
if (геолокация в списке заблокированных стран) then (да)
    :заявка отклонена;
    stop
else (нет)
    :проверка содержания контента;
    fork
        :нарушение авторских прав;
    fork again
        :мошенничество;
    fork again
        :наличие опасного контента;
    fork again
        :излишняя нагота;
    fork again
        :дискриминация;
    fork again
        :травмоопасный контент;
    fork again
        :жалобы от других пользователей;
    end fork
    if (Заявка прошла проверку) then (да)
        :заявка одобрена;
        stop
    else (нет)
        :заявка отклонена;
        stop
    endif
@enduml