@startuml Диаграмма контекста
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Диаграмма контекста

Person(client, "Клиент", "Пользователь нашей системы")

System(storage, "Система хранилищ данных", "Хранит видео, закодированные видео, метаданные, кэш метаданных")
System(server, "Веб-сервер", "Используется для обработки входящих запросов от клиента. В зависимости от типа запроса он направляет запрос на сервер приложений или сервер перекодирования.")
System(API, "Система серверов API", "Содержит балансировщик нагрузки, сервера апи")
System(code, "Сервер транскодирования", "Преобразует видео в различные форматы и разрешения")
System(db, "База данных", "Хранение данных о пользователе, видео")
System(anal, "Система рекомендаций", "Подбирает рекомендации по тегам, лайкам, просмотрам")

Rel(client, server, "Отправляет запрос")
Rel(server, API, "Переадресация запроса")
Rel(server, code, "Переадресация запроса")
Rel(API, storage, "Загрузка данных")
Rel(API, db, "Загрузка данных")
Rel(db, anal, "Данные")
Rel(anal, API, "Отдает рекомендации")

@enduml