@startuml
[*] --> Незарегистрированный_Пользователь
Незарегистрированный_Пользователь --> Незарегистрированный_Пользователь_С_Логином : Ввод логина
Незарегистрированный_Пользователь_С_Логином --> Незарегистрированный_Пользователь_С_Логином_И_Паролем : Ввод пароля
Незарегистрированный_Пользователь_С_Логином_И_Паролем --> Зарегистрированный_Пользователь : Отправляет данные
Зарегистрированный_Пользователь --> Подтвержденный_Зарегистрированный_Пользователь : Подтверждение с помощью кода
Подтвержденный_Зарегистрированный_Пользователь --> [*]
@enduml