@startuml
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Выбирает способ оплаты
    Client -> UI: Вводит сумму пополнения
    UI -> Server: Передает данные
    Server -> Db: Запрос о записи данных
    Db -> Db: подготовка ответа
    Server <-- Db: Отправка ответа
    UI <-- Server: Возврат сообщения об успешной оплате
    Client <-- UI: Ответ от UI

@enduml