@startuml
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Выбирает способ показа рекламы
    UI -> Client: Отображает выбранные данные
    Client -> UI: Выбирает категорию видео
    UI -> Client: Отображает выбранные данные
    Client -> UI: Выбирает тариф оплаты
    UI -> Client: Отображает выбранные данные
    Client -> UI: Вводит ограничение количества оплат
    UI -> Client: Отображает выбранные данные
    Client -> UI: Загружает видео рекламы
    UI -> Server: Передача данных
    Server -> Db: Запрос о записи данных
    Db -> Db: подготовка ответа
    Server <-- Db: Отправка ответа
    UI <-- Server: Возврат сообщения об успешной загрузке
    Client <-- UI: Ответ от UI

@enduml