@startuml
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Загружает видео
    UI -> Server: Передача видео
    Server -> Db: Запрос о записи данных
    Db -> Db: подготовка ответа
    Server <-- Db: Отправка ответа
    UI <-- Server: Возврат сообщения об успешной загрузке
    Client <-- UI: Ответ от UI

    Client -> UI: Добавили название, описание, возрастное ограничение, теги, настройки комментирования
    UI -> Server: Передача данных
    Server -> Db: Запрос о записи данных
    Db -> Db: подготовка ответа
    Server <-- Db: Отправка ответа
    UI <-- Server: Возврат сообщения об успешной загрузке
    Client <-- UI: Ответ от UI

@enduml