@startuml
[*] --> Незарегистрированная_Организация : Ввод данных организации
Незарегистрированная_Организация --> Зарегистрированная_Организация
state "Зарегистрированная_Организация" as Подтверждение
Зарегистрированная_Организация --> Подтверждение : Подтверждение через email
Подтверждение : Подтвержденное письмо
state "Зарегистрированная_Организация" as Документы
Подтверждение --> Документы : Загрузка документов
Документы : Подтвержденное письмо
Документы : Загруженные документы
state "Подтвержденная Организация" as Организация
Документы --> Организация : Подвтерждение организации
@enduml