@startuml
start
switch(:Выбор способа показа рекламы)
case (pre-roll)
    :показ рекламы в начале видео;
case (mid-roll)
    :показ рекламы в середине видео;
case (pause-roll)
    :показ рекламы на паузе;
case (post-roll)
    :показ рекламы в конце видео;
case (multi-roll)
    :показ рекламы в начале, середине, конце видео;
case (wow-roll)
    :показ вылетающей рекламы;
case (overlay)
    :показ рекламы в виде баннера;
case (TrueViewIn-Stream)
    :показ рекламы с пропуском через 5с;
case (In-stream)
    :показ рекламы без пропуска;
case (bamperAds)
    :показ рекламы видео 6с;
endswitch
:Выбран способ показа рекламы;

switch(:Выбор категории видео)
case (Игры)
    :категория игры;
case (Лайфхак)
    :категория лайфхак;
case (Челлендж)
    :категория челлендж;
case (Пранк)
    :категория пранк;
case (Туториал)
    :категория туториал;
case (Шоу)
    :категория шоу;
case (Влог путешествий)
    :категория влог путешествий;
case (Пародии)
    :категория пародии;
case (Переозвучка)
    :категория переозвучка;
case (Блог еды)
    :категория блог еды;
case (Наука)
    :категория наука;
case (Красота здоровья)
    :категория красота здоровья;
case (Остальное)
    :категория озвучка;
endswitch
:выбрана категория видео;
:выбор тарифа оплаты;
:установка ограничения количества оплат;
:загрузка видео;
stop
@enduml