@startuml
start
:Ввод логина и пароля;
:Регистрация;
repeat :Отправка сообщения на email
    :Ввод пришедшего кода;
    if (код верен) then (да)
        :Вывод правил сервиса;
        stop
    endif
repeatwhile
@enduml