@startuml
start
:Ввод данных организации;
:Регистрация организации;
repeat :Отправка ссылки на email
    if (Подтвердили ссылку) then (да)
        :загрузка документов, подтверждающих 
        существование организации;
        :Организация  подвтерждена;
        stop
    endif
repeatwhile
@enduml